import gym

from myutils.gym_custom.gym_custom import MountainCarEnvWrapper


class ModelTrainingAndValidationParameters:

    #ENVIRONMENT INFO
    ENVIRONMENT = MountainCarEnvWrapper(gym.make('MountainCar-v0').env)
    NUMBER_OF_ACTIONS = ENVIRONMENT.action_space.n

    #TRAINING PROCESS SETUP
    TIME_STEPS_IN_EPISODE = 300
    NUMBER_OF_TRAINING_EPISODES = 150
    MAXIMUM_NUMBER_OF_STATES_IN_BUFFER = 50000
    MINIMUM_SAMPLES_TO_START_TRAINING = TIME_STEPS_IN_EPISODE * 5
    BATCH_SIZE = 32
    FRAMES_SKIP = 4

    #NETWORK SETUP
    FRAMES_IN_STATE = 4
    FRAME_HEIGHT = 48
    FRAME_WIDTH = 48

    UPDATE_TRAINING_NET_THRESHOLD = 35
    SAVE_MODEL_THRESHOLD = 10

    #VALIDATION PARAMETERS
    NUMBER_OF_EVALUATION_EPISODES_PER_MODEL = 100
